#!/bin/sh

# SPDX-FileCopyrightText: 2024, 2025, 2026 SURF B.V.
# SPDX-License-Identifier: EPL-2.0 WITH Classpath-exception-2.0

if bb -e '(System/exit 0)' 2>/dev/null; then
    RUNTIME="bb"
else
    RUNTIME="clojure -M"
fi

${RUNTIME} -m nl.surf.eduhub-validator.main "$@"
