# SPDX-FileCopyrightText: 2024, 2025, 2026 SURF B.V.
#
# SPDX-License-Identifier: EPL-2.0 WITH Classpath-exception-2.0

name: Check dependency vulnerabilities

on:
  push:
  schedule:
    - cron: '0 1 * * 1,2,3,4,5' # every workday

jobs:
  "NVD-check":
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
    - uses: jomco/clojure-action@4259a5767c4dac675217229f2facf927211ff76b # v1
      with: { m2-cache-key: m2-nvd }

    - name: Check clojure dependencies with NVD
      run: make watson
